name: Build and deploy The Library App API

on: [push]

env:
  SERVICE_NAME: code-library-api
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/code-library-api

jobs:
  build-container:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker gcr.io

      - name: Build and Push Container
        run: |
          docker build --tag $IMAGE_NAME:${{ github.sha }} .
          docker build --tag $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest
  test-run:
    needs: build-container
    runs-on: ubuntu-20.04
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy to Cloud Run
        id: deploy-run
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: ${{ env.SERVICE_NAME }}
          image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          region: europe-west3
          flags: --allow-unauthenticated
      - name: Test Deployment
        run: curl "${{ steps.deploy-run.outputs.url }}"
